### ISSUE TITLE
Integrating Maven build tool

### ISSUE THREAD

**Issue by levFarkas** [Flezy/EmailValidation#2]

**Comment by levFarkas** [comment]
maven letöltése, basic pom.xml hozzáadása és build.

**Comment by becgabi** [comment]
A pom.xml elkészült.

**Comment by Geri044** [comment]
Változtatások pusholva. Build sikeres.

**Comment by micskeiz** [comment]
Megnéztétek, hogy mit fordított a Maven és mit csinált a build? Ez egy C# alkalmazás, alapból ezt a Maven nem fogja lefordítani, de nincs is rá szükség, mert az msbuild ugyanezt megcsinálja.

Ha ragaszkodtok a Maven-hez, akkor érdemes kiegészíteni a pom.xml-t, mert így nem csinál semmit. De inkább törölhetitek a pom.xml-t, mert csak zavaró. A target könyvtár pedig generált kimeneti könyvtár, nem kell verziókezelőbe rakni.
