### ISSUE TITLE
Analyzing code

### ISSUE THREAD

**Issue by Geri044** [Flezy/EmailValidation#3]

**Comment by aladar49** [comment]
Futtattuk a code analyzer-t a projekten és 8 warning-et kaptunk.

**Comment by Geri044** [comment]
Új branch, melyben az előbb említett 8 warning-ból 6 javítva lett.

**Comment by levFarkas** [comment]
Mergeltük a branchet, a review megtörtént a manual analyze issue-ban.

**Comment by micskeiz** [comment]
OK
