### ISSUE TITLE
Unit tesztek bővítése

### ISSUE THREAD

**Issue by levFarkas** [Flezy/EmailValidation#6]

**Comment by Geri044** [comment]
Kódlefedettség ellenőrzése, bővítési ötletek nyerése céljából

**Comment by Geri044** [comment]
Az ellenőrzésből kiderült, hogy az EmailAttribute -nak az alap konstruktora nincs használva.
Két új tesztesetet fogunk implementálni, melyben:
- Tiltjuk a TopLevelDomain-t is.
- Ellenőrizzük hogy TopLevelDomain-es és nem TopLevelDomaines email címmel megfelelően validálódik.

**Comment by Geri044** [comment]
A két új teszteset implementálva futását ellenőriztem.
https://github.com/Flezy/EmailValidation/commit/130f3588cead61908b500d3e0d3fa353495960ee
A CodeCoverage a következőképpen módosult:
![image](https://cloud.githubusercontent.com/assets/11063384/25636734/96907708-2f82-11e7-8665-e79bc0a96f85.png)

**Comment by aladar49** [comment]
Tesztelés során nem vizsgáljuk meg az emailt null értéke esetén. 

Erre létrehoztam a TestNullAddresses() testet, mely javított a kódlefedettségen.
![image](https://cloud.githubusercontent.com/assets/26622552/25638044/5e530036-2f87-11e7-8b9c-0edd6f9e22c5.png)
https://github.com/Flezy/EmailValidation/commit/54bd58104562621bf63ce8bfdb392064555f402d

**Comment by Geri044** [comment]
További ellenőrzések során még két eset vizsgálatára hoztam létre egy tesztesetet.
Feltöltöttem a változtatásokat egy új branchbe: InvalidIntern
https://github.com/Flezy/EmailValidation/commit/14ed919949671d8299c3fb40ca843dffe468d010
Ebbe a branchbe egy új teszteset van: TestInvalidInternational, ahol megnézzük, hogy nemzetközi karaktereket elfogad-e ha nem kéne hogy elfogadjon. Itt használjuk az eddig nem használt Validate függvény egy paraméteres változatát.
A kódlefedettség javult:
![image](https://cloud.githubusercontent.com/assets/11063384/25638640/54c8f6fe-2f89-11e7-9f2b-abbc701e906d.png)
Pull request-et létrehozom merge-elés céljából.

**Comment by aladar49** [comment]
A tesztelés eddig nem tért ki a rövid ipv címek vizsgálatára ezt pótoltam a TestEnoughCharacterOfIPV4() teszttel. 
![image](https://cloud.githubusercontent.com/assets/26622552/25641241/69dc249e-2f93-11e7-915c-1e2d3d6496bb.png)
https://github.com/Flezy/EmailValidation/commit/0d281ce77394e79709264bf9db2120ee7d827a77

**Comment by Geri044** [comment]
A unit teszteket bővítettük 5 új tesztesettel. Ezek pár további speciális esetet és funkciót tezstelnek. Az issue-t lezárhatjuk.
