### ISSUE TITLE
Kódlefedettség ellenőrzése javítása

### ISSUE THREAD

**Issue by levFarkas** [Flezy/EmailValidation#7]

**Comment by levFarkas** [comment]
## **Code coverage beállítás**

### Első lépésként a szükséges függőségeket letöltjük.

- OpenCover
- ReportGenerator

A NuGet Package Manager Console-ba beírjuk a következő parancsokat
`Install-Package OpenCover`
`Install-Package ReportGenerator`

### Ezt követően létrehozunk egy batch file-t a root mappában
A batch így néz ki: 
`.\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe `
`-register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\MSTest.exe" `
`-targetargs:"/noresults /noisolation /testcontainer:"".\UnitTests\bin\Debug\UnitTests.dll"  `
`-excludebyattribute:*.ExcludeFromCodeCoverage* `
`-hideskipped:All `
`-output:.\MyProject_coverage.xml`

A solution-t buildeljük, és futtatjuk a batch file-t

A változtatásokat Flezy push-olta:
https://github.com/Flezy/EmailValidation/commit/e838a5d550fba8c2c71322831ad94aa16828dd39

**Comment by becgabi** [comment]
# Report Generator beállítás
## A batch file kikerült a projekt root mappájába
A report generator használatához ezeket a sorokat kellett a szkriptbe írni:
`"%~dp0packages\ReportGenerator.2.5.7\tools\ReportGenerator.exe" -reports:"%~dp0EmailValidation_coverage.xml" -targetdir:"%~dp0\Output"`

Majd az szkript futása után rögtön megnyílik a generált html a következő sornak köszönhetően:
`start "report" "%~dp0\Output\index.htm"`

Változtatások push-olva becgabi által:
https://github.com/Flezy/EmailValidation/commit/abd4030f141a59f6e8ecb6688ccde28d6c7d67c1

**Comment by levFarkas** [comment]
A Unit tesztek nem jelentek meg a Visual Studio-ban és az OpenCover sem találtam meg őket.

> Javítva!

> Megoldás: NUnitTestAdapter package

**Comment by becgabi** [comment]
## Elölről kezdtük a batch file írását, mert vakvágányra jutottunk
A targetet NUnit-ra írtuk át.
A végleges batch file:
`packages\OpenCover.4.6.519\tools\OpenCover.Console -target:packages\NUnit.ConsoleRunner.3.6.1\tools\nunit3-console.exe -targetargs:UnitTests\bin\Debug\UnitTests.dll -register:user
`

`packages\ReportGenerator.2.5.7\tools\ReportGenerator.exe -reports:results.xml -targetdir:MetricResults`

**Comment by Geri044** [comment]
A változtatásokat pusholtam: 
https://github.com/Flezy/EmailValidation/commit/7e5dc8f8f515a26ccc538924836990ecd7ab1707

**Comment by aladar49** [comment]
Az ellenőrzést elvégeztük. Következhet a javítás.
![image](https://cloud.githubusercontent.com/assets/26622552/25633508/a406968e-2f77-11e7-8125-d2f90a05215e.png)

**Comment by Geri044** [comment]
https://cloud.githubusercontent.com/assets/26622552/25641241/69dc249e-2f93-11e7-915c-1e2d3d6496bb.png

**Comment by Geri044** [comment]
Az előző commentben belinkeltem a képet amin látható, hogy a tesztek bővítése javított a lefedettségen.

**Comment by aladar49** [comment]
A kódlefedettség mérése sikeres volt. Az új tesztesetek kitérnek a tesztelés során még bejáratlan kódrészletek jelenetős részét. Az issue lezárható.
